name: Rust build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:  # TODO
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: schnek
        path: target/${{ matrix.BUILD_TARGET }}/schnek  # TODO