name: Lint and test

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  Check-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Check clippy
      run: cargo clippy --all-targets
  Build-and-test:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get -y install libasound2-dev
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose